baseURL = "https://zhy07.top"
locale = "zh-CN"
title = "zhy's blog"
hasCJKLanguage = true

# 内容管理
defaultContentLanguage = "zh"
[pagination]
  pagerSize = 10
summaryLength = 140

# 输出
[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML", "RSS"]

# 分类
[taxonomies]
  tag = "tags"
  category = "categories"

# 渲染
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
# 友链字段：name、url、description、category（可选）
friendLinks = [
  {name = "lzh的快乐小窝", url = "https://cnblogs.com/linzhuohang", description = ""},
  {name = "HelloGitHub", url = "https://hellogithub.com", description = "分享 GitHub 上有趣、入门级的开源项目", category = "推荐"}
]

# 服务器
[server]
    for = "/**"
    [server.headers.values]
      X-Frame-Options = "DENY"
      X-Content-Type-Options = "nosniff"